import { ItemDescription } from "src/items/entities/item.entity";

export const mockCategoryTree: Record<string, string[]> = {
  ipod: [
    "Electrónica, Audio y Video",
    "iPod",
    "Reproductores",
    "iPod Touch",
    "32GB",
  ],
  notebook: ["Tecnología", "Computación", "Laptops", "Notebooks", "Lenovo"],
  camera: [
    "Fotografía y Video",
    "Cámaras Digitales",
    "Cámaras Réflex",
    "Canon",
    "EOS",
  ],
};

export const MOCKED_ITEMS = [
  // iPod category
  {
    id: "MLA1",
    title: "iPod Touch 32GB - Space Gray",
    price: { currency: "ARS", amount: 120000, decimals: 0 },
    picture: "https://example.com/ipod1.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 87,
    description: "iPod Touch de 7ma generación con 32GB de almacenamiento.",
    category: "ipod",
  },
  {
    id: "MLA4",
    title: "iPod Nano 16GB - Silver",
    price: { currency: "ARS", amount: 90000, decimals: 0 },
    picture: "https://example.com/ipod2.jpg",
    condition: "used",
    free_shipping: false,
    sold_quantity: 120,
    description: "iPod Nano compacto, ideal para llevar música a todos lados.",
    category: "ipod",
  },
  {
    id: "MLA5",
    title: "iPod Classic 160GB - Black",
    price: { currency: "ARS", amount: 110000, decimals: 0 },
    picture: "https://example.com/ipod3.jpg",
    condition: "used",
    free_shipping: true,
    sold_quantity: 65,
    description: "Clásico iPod de alta capacidad para verdaderos fanáticos.",
    category: "ipod",
  },

  // Notebook category
  {
    id: "MLA2",
    title: "Notebook Lenovo IdeaPad 3 - Ryzen 5",
    price: { currency: "ARS", amount: 250000, decimals: 0 },
    picture: "https://example.com/lenovo1.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 34,
    description: "Notebook con procesador AMD Ryzen 5 y 8GB de RAM.",
    category: "notebook",
  },
  {
    id: "MLA6",
    title: "Notebook HP 250 G8 - Intel i3",
    price: { currency: "ARS", amount: 230000, decimals: 0 },
    picture: "https://example.com/hp.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 28,
    description: "Notebook económica para tareas básicas con Windows 11.",
    category: "notebook",
  },
  {
    id: "MLA7",
    title: "Notebook Dell Inspiron 15 - i7 11va Gen",
    price: { currency: "ARS", amount: 370000, decimals: 0 },
    picture: "https://example.com/dell.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 15,
    description: "Alto rendimiento con 16GB RAM y SSD de 512GB.",
    category: "notebook",
  },

  // Camera category
  {
    id: "MLA3",
    title: "Cámara Réflex Canon EOS 4000D",
    price: { currency: "ARS", amount: 210000, decimals: 0 },
    picture: "https://example.com/canon1.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 45,
    description: "Cámara réflex digital ideal para fotografía profesional.",
    category: "camera",
  },
  {
    id: "MLA8",
    title: "Cámara Sony Alpha a6000 Mirrorless",
    price: { currency: "ARS", amount: 320000, decimals: 0 },
    picture: "https://example.com/sony.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 20,
    description: "Compacta y potente, con enfoque automático ultrarrápido.",
    category: "camera",
  },
  {
    id: "MLA9",
    title: "Cámara Nikon D3500 Kit 18-55mm",
    price: { currency: "ARS", amount: 295000, decimals: 0 },
    picture: "https://example.com/nikon.jpg",
    condition: "new",
    free_shipping: false,
    sold_quantity: 31,
    description: "Ideal para iniciarte en la fotografía réflex.",
    category: "camera",
  },
  {
    id: "MLA10",
    title: "Canon EOS Rebel T7 - Full HD",
    price: { currency: "ARS", amount: 275000, decimals: 0 },
    picture: "https://example.com/canon2.jpg",
    condition: "new",
    free_shipping: true,
    sold_quantity: 18,
    description: "Captura imágenes y videos en alta calidad.",
    category: "camera",
  },
];
